name: Build Scala 2.13, Spark 3.2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: mvn clean verify -Plicense-check,spark-3.2,scala-2.13,code-coverage
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.4
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 0.0
        min-coverage-changed-files: 80.0
        title: JaCoCo code coverage report - Scala 2.13 & Spark 3.2
        update-comment: true
    - name: Get the Coverage info
      run: |
        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
    - name: Fail PR if changed files coverage is less than 80%
      if: ${{ steps.jacoco.outputs.coverage-changed-files < 80.0 }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Changed files coverage is less than 80%!')
