name: Binary Compatibility

on:
  pull_request:
    branches: [ master, branch-6, branch-5 ]
    types: [ opened, edited, synchronize, reopened ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [ 2.13 ]
    name: Scala ${{ matrix.scala }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ matrix.scala }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.scala }}-
      - name: Check binary compatibility
        run: mvn clean test -DskipTests -Pcompatibility-check
